apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registrykubedev.azurecr.io/pedelogo-catalogo:1.0.0
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: api-configmap
          env:
            - name: Mongo__User
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret
            - name: Mongo_Password
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret
      imagePullSecrets:
        - name: acr-kubedev

# para utilizar com o ConfigMap
#            - name: Mongo__User
#              valueFrom:
#                configMapKeyRef:
#                  key: MONGO_INITDB_ROOT_USERNAME
#                  name: mongodb-configmap
#            - name: Mongo_Password
#              valueFrom:
#                configMapKeyRef:
#                  key: MONGO_INITDB_ROOT_PASSWORD
#                  name: mongodb-configmap