apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ivanjuniordocker/pedelogo-catalogo:1.0.0
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          imagePullPolicy: Always
          env:
            - name: Mongo__Host
              value: "mongodb-service"
            - name: Mongo__User
              value: "mongouser"
            - name: Mongo_Password
              value: "mongopwd"
            - name: Mongo__Port
              value: "27017"
            - name: Mongo__DataBase
              value: "admin"
            